dist: trusty
sudo: false

language: node_js

node_js:
  - "8"

addons:
  chrome: stable

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm

install:
  - npm install

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test -- --no-watch --code-coverage --no-progress --browsers ChromeCI && npm run codecov
